apiVersion: v2
name: webhook-tester
description: Codeveros Webhook Tester
type: application
version: 1.0.0
appVersion: "2.0.0"
home: https://coveros.com
maintainers:
  - name: justin-coveros
    email: justin.hollingsworth@coveros.com
