replicaCount: 1

image:
  repository: ghcr.io/coveros/webhook-tester
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080
  nodePort:

ingress:
  annotations: {}
  enabled: false
  host: ""
  path: "/"
  tlsSecretName: ""
