replicaCount: 1

image:
  repository: ghcr.io/coveros/codeveros-gateway
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080

ingress:
  annotations: {}
  enabled: false
  host: ""
  path: "/"
  tlsSecretName: ""
