{{- if .Values.ingress.enabled }}
  {{ $latestVersion := semverCompare ">=1.19-0" .Capabilities.KubeVersion.Version }}
  {{- if $latestVersion }}
apiVersion: networking.k8s.io/v1
  {{- else }}
apiVersion: networking.k8s.io/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ include "webhook-tester.fullname" . }}
  labels:
  {{- include "webhook-tester.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            {{- if $latestVersion }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "webhook-tester.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
            {{- else }}
            backend:
              serviceName: {{ include "webhook-tester.fullname" . }}
              servicePort: {{ .Values.service.port }}
      {{- end }}
      {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host | quote }}
  {{- end }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
{{- end }}
