apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhook-tester.fullname" . }}
  labels:
  {{- include "webhook-tester.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort)))}}
      nodePort: {{ .Values.service.nodePort }}
      {{end}}
  selector:
  {{- include "webhook-tester.selectorLabels" . | nindent 4 }}
